dist: xenial

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

language: python

python:
  - "3.7"

install:
  - "curl -O https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip"
  - "unzip -o chromedriver_linux64.zip"
  - "sudo mv -f chromedriver /usr/local/bin/chromedriver"

script:
  - "python setup.py test"
